version: '3'
services:
  db:
    image: postgres:14.2-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=myappdb
      - POSTGRES_USER=rick
      - POSTGRES_PASSWORD=weakzombies

  web:
    build: .
    stdin_open: true
    tty: true
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/zssn
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  gem_cache:
  db_data:
  node_modules:

networks:
  default:
    name: zssn_default
